approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^No'
reset_on_push: true
author_approval: ignored
reviewers:
    -
        name: admins
        required: 2
        members:
            - a_user
            - anotheruser
    -
        name: backend_devs
        required: 1
        members:
            - backender_one
    -
        name: designers
        required: 1
        members:
            - designerA
            - designerB
